version: "3"

services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  traefik:
    container_name: traefik
    # The official v2 Traefik docker image
    image: traefik:latest
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "--api.dashboard=true"
      - "--api=true"
      - "--providers.docker"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entryPoint.permanent=true"
      - "--global.sendAnonymousUsage=true"
      - "--providers.file.directory=/config"
      - "--providers.file.watch=true"
      - "--certificatesResolvers.cloudflare.acme.storage=/acme.json"
      - "--certificatesResolvers.cloudflare.acme.dnsChallenge.provider=cloudflare"
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
      - PROXY_HOSTNAME=${PROXY_HOSTNAME}
      - TARGET_IP=${TARGET_IP}
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "443:443"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./Traefik/acme.json:/acme.json
      - ./Traefik/config:/config
    labels:
      - traefik.http.routers.proxy.tls=true
      - traefik.http.routers.proxy.tls.certresolver=cloudflare
      - traefik.http.routers.proxy.tls.domains[0].main=fireword.xyz
      - traefik.http.routers.proxy.tls.domains[0].sans=*.fireword.xyz
  authelia:
    container_name: authelia
    image: authelia/authelia:latest
    command: ["--config", "/config/authelia.yml"]
    volumes:
      - "./Authelia:/config"
