http:
  routers:
    adguard-router:
      rule: 'Host(`adguard.{{ env "PROXY_HOSTNAME" }}`)'
      service: adguard-service
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare

  services:
    adguard-service:
      loadBalancer:
        servers:
          - url: 'http://{{ env "TARGET_IP"  }}:82'
