http:
  routers:
    bazarr-router:
      rule: 'Host(`bazarr.{{ env "PROXY_HOSTNAME" }}`)'
      service: bazarr-service
      middlewares:
        - authelia
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare

  services:
    bazarr-service:
      loadBalancer:
        servers:
          - url: 'http://{{ env "TARGET_IP"  }}:6767'
