http:
  routers:
    proxydev-router:
      rule: 'Host(`proxydev.{{ env "PROXY_HOSTNAME" }}`)'
      service: proxydev-service
      middlewares:
        - authelia
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare

  services:
    proxydev-service:
      loadBalancer:
        servers:
          - url: 'http://proxy:8000'
