http:
  routers:
    dashboard-router:
      rule: 'Host(`proxy.{{ env "PROXY_HOSTNAME" }}`)'
      service: dashboard-service
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
        domains:
          - main: '{{ env "PROXY_HOSTNAME" }}'
            sans:
              - '*.{{ env "PROXY_HOSTNAME" }}'
  services:
    dashboard-service:
      loadBalancer:
        servers:
          - url: "http://traefik:8080"
