http:
  routers:
    readarr-router:
      rule: 'Host(`readarr.{{ env "PROXY_HOSTNAME" }}`)'
      service: readarr-service
      middlewares:
        - authelia
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare

  services:
    readarr-service:
      loadBalancer:
        servers:
          - url: 'http://{{ env "TARGET_IP"  }}:5656'
