http:
  routers:
    radarr-router:
      rule: "Host(`radarr.{{ env "HOSTNAME" }}`)"
      service: radarr-service
      
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
    
  services:
    radarr-service:
      loadBalancer:
        servers:
          - url: "http://{{ env "TARGET_IP" }}:7878"
    
