http:
  routers:
    readarr-router:
      rule: "Host(`readarr.{{ env "HOSTNAME" }}`)"
      service: readarr-service
      
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
    
  services:
    readarr-service:
      loadBalancer:
        servers:
          - url: "http://{{ env "TARGET_IP" }}:5656"
    
